#ifndef STR_MEM_DEV_H
#define STR_MEM_DEV_H

#define PRFT_IOCTL_BASE 0xA4

#define IOCTL_TS_STOP _IO(PRFT_IOCTL_BASE, 0x00)
#define IOCTL_TS_WAIT _IO(PRFT_IOCTL_BASE, 0x01)
#define IOCTL_TS_START _IO(PRFT_IOCTL_BASE, 0x02)
#define IOCTL_TS_SET _IOW(PRFT_IOCTL_BASE, 0x03, uint32_t)

#endif